FROM openjdk:8u222                                                              
                                                                                
MAINTAINER DanDan_OvO 1021461238@qq.com                                         
                                                                                
#安 装 依 赖                                                                        
RUN apt-get update && \                                                         
    apt-get install -y openssh-server && \                                      
    apt-get install -y passwd && \                                              
    apt-get install -y tmux && \                                                
    rm -rf /var/lib/apt/lists/* && \                                            
    apt-get clean                                                               
                                                                                
#设 置 密 码                                                                        
RUN echo 'root:root' |chpasswd                                                  
                                                                                
#设 置 sshd                                                                       
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config 
&& \sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config                   
#创 建 sshd目 录                                                                    
RUN mkdir -p /var/run/sshd                                                      
                                                                                
#创建服务端文件夹                                                                            
RUN mkdir -p /server                                                            
                                                                                
#添加服务器核心                                                                         
ADD mc.jar /server/                                                             
                                                                                
#设 置 工 作 目 录                                                                    
WORKDIR /server                                                                 
                                                                                
#echo.txt                                                                       
RUN echo eula=true > eula.txt                                                   
                                                                                
#暴 露 端 口                                                                        
EXPOSE 22                                                                       
EXPOSE 25565                                                                    
                                                                                
#设 置 容 器 启 动 参 数                                                                
ENTRYPOINT tmux new-session -d -s server 'java -Xmx4G -jar /server/mc.jar' & /us
r/sbin/sshd -D
